POST http://localhost:8080/CA1/api/persons/
Content-Type: application/json

{"personFirstname": "Frederik23", "personLastname": "Hess", "personEmail": "Frederik@hess.dk"}

###
GET http://localhost:8080/CA1/api/persons/city?zipcode=3450&cityname=alleroed
Content-Type: application/json

###
GET http://localhost:8080/CA1/api/persons/count/hobby?hobby=badminton
Content-Type: application/json

###
GET http://localhost:8080/CA1/api/persons/count/zip?zip=3450
Content-Type: application/json

###
GET http://localhost:8080/CA1/api/persons/all/
Content-Type: application/json

###
DELETE http://localhost:8080/CA1/api/addresses/delete/1
Content-Type: application/json


